name: Build Docker Image

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  api-build-container:
    name: api-build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: build Docker image
      run: |
        docker build --file apps/api/Dockerfile --tag ghcr.io/${{ github.repository_owner }}/api:${{ github.run_number }} apps/api      

    - name: Tag image as latest
      run: docker tag ghcr.io/${{ github.repository_owner }}/api:${{ github.run_number }} ghcr.io/${{ github.repository_owner }}/api:latest